name: Build and and deploy DSF packages

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Deployment target"
        required: true
        default: "dev"
        type: choice
        options:
        - dev
        - unstable-3.5
        - stable-3.5
      version:
        description: "Version"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # Check out CANlib
      - uses: actions/checkout@v3
        with:
          repository: "Duet3D/CANlib"
          ref: "3.5-dev"

      # Check out CoreN2G
      - uses: actions/checkout@v3
        with:
          repository: "Duet3D/CoreN2G"
          ref: "3.5-dev"

      # Check out FreeRTOS
      - uses: actions/checkout@v3
        with:
          repository: "Duet3D/FreeRTOS"
          ref: "3.4-dev"

      # Check out RRFLibraries
      - uses: actions/checkout@v3
        with:
          repository: "Duet3D/RRFLibraries"
          ref: "3.5-dev"

      # Check out RRFLibraries
      - uses: actions/checkout@v3
        with:
          repository: "Duet3D/DuetWiFiSocketServer"
          ref: "dev"

      # Check out RepRapFirmware
      - uses: actions/checkout@v3
        with:
          repository: "Duet3D/RepRapFirmware"
          ref: "3.5-dev"

      # Prepare Eclipse-CDT
      - name: Set up Eclipse-CDT
        run: |
          sudo apt-get install -y bsdtar default-jre
          sudo snap install --classic eclipse

      # Prepare ARM cross compiler
      - name: Set up ARM GCC
        run: |
          curl -L -O "https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2?rev=78196d3461ba4c9089a67b5f33edf82a&hash=5631ACEF1F8F237389F14B41566964EC"
          bsdtar -x -f "./gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2\?rev=78196d3461ba4c9089a67b5f33edf82a\&hash=5631ACEF1F8F237389F14B41566964EC"

      # Prepare workspace
      - name: Set up workspace
        run: |
           /opt/eclipse/eclipse --launcher.suppressErrors -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild -data /tmp/workspace -importAll $GITHUB_WORKSPACE

      # Build RepRapFirmware (MB6HC)
      - name: Build Duet3_MB6HC
        run: |
           /opt/eclipse/eclipse --launcher.suppressErrors -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild -data /tmp/workspace -E ArmGccPath=$GITHUB_WORKSPACE/gcc-arm-none-eabi-10.3-2021.10/bin -cleanBuild "RepRapFirmware/Duet3_MB6HC"

