name: Build and and deploy firmware

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Deployment target"
        required: true
        default: "dev"
        type: choice
        options:
        - dev
        - unstable-3.5
        - stable-3.5
      version:
        description: "Version"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: "Check out CANlib"
        uses: actions/checkout@v3
        with:
          repository: "Duet3D/CANlib"
          ref: "3.5-dev"
          path: "./CANlib"

      - name: "Check out CoreN2G"
        uses: actions/checkout@v3
        with:
          repository: "Duet3D/CoreN2G"
          ref: "3.5-dev"
          path: "./CoreN2G"

      - name: "Check out FreeRTOS"
        uses: actions/checkout@v3
        with:
          repository: "Duet3D/FreeRTOS"
          ref: "3.4-dev"
          path: "./FreeRTOS"

      - name: "Check out RRFLibraries"
        uses: actions/checkout@v3
        with:
          repository: "Duet3D/RRFLibraries"
          ref: "3.5-dev"
          path: "./RRFLibraries"

      - name: "Check out DuetWiFiSocketServer"
        uses: actions/checkout@v3
        with:
          repository: "Duet3D/DuetWiFiSocketServer"
          ref: "dev"
          path: "./DuetWiFiSocketServer"

      - name: "Check out RepRapFirmware"
        uses: actions/checkout@v3
        with:
          repository: "Duet3D/RepRapFirmware"
          ref: "3.5-dev"
          path: "./RepRapFirmware"

      - name: "Prepare CrcAppender"
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download -R Duet3D/CrcAppender --pattern "CrcAppender-linux-x64"
          chmod +x ./CrcAppender-linux-x64
          mv ./CrcAppender-linux-x64 ./CrcAppender
          export PATH=$(pwd):$PATH

      - name: "Set up Eclipse-CDT"
        run: |
          sudo apt-get install -y libarchive-tools default-jre
          curl -L -O "https://pkg.duet3d.com/eclipse-cpp-2023-09-R-linux-gtk-x86_64.tar.gz"
          sudo bsdtar -x -f ./eclipse-cpp-2023-09-R-linux-gtk-x86_64.tar.gz -C /opt

      - name: "Set up ARM GCC"
        run: |
          curl -L -o ./arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi.tar.xz "https://developer.arm.com/-/media/Files/downloads/gnu/12.2.rel1/binrel/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi.tar.xz?rev=7bd049b7a3034e64885fa1a71c12f91d&hash=732D909FA8F68C0E1D0D17D08E057619"
          bsdtar -x -f ./arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi.tar.xz

      - name: "Set up Eclipse workspace"
        run: |
          /opt/eclipse/eclipse --launcher.suppressErrors -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild -data ./workspace -E ArmGccPath=$GITHUB_WORKSPACE/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi/bin -importAll ./

      - name: "Build Duet3_MB6HC"
        run: |
          /opt/eclipse/eclipse --launcher.suppressErrors -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild -data ./workspace -E ArmGccPath=$GITHUB_WORKSPACE/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi/bin -cleanBuild "RepRapFirmware/Duet3_MB6HC"

